#Uniform random numbers in the textbook:  Compose a program that writes five uniform random floats between 0 and 1 (generated by the random.random() function.), their average value, and their minimum and maximum value. Use the built-in max() and min() functions.
import sys
import stdio
import random

number_list = []
for i in range(5):
    number_list.append(random.random())

avg = sum(number_list) / len(number_list)
stdio.write(f"Average number = {avg}\n")
stdio.write(f"Max number     = {max(number_list)}\n")
stdio.write(f"Min number     = {min(number_list)}\n")